# Cloudflare Workers 配置檔案
# 網站：cardioanalytics.twinhao.com

name = "cardioanalytics-worker"
main = "worker.js"
compatibility_date = "2025-10-15"  # 使用最新的 compatibility date
account_id = "562f1caaf716714f4913ae40a1772c76" # 請填入您的 Cloudflare Account ID

# Worker 類型：模組語法
workers_dev = true

# 已使用 Custom Domains 綁定域名，不需要 routes
# Dashboard: Workers & Pages → cardioanalytics-worker → Settings → Domains & Routes


# 資產綁定 - 將靜態檔案打包進 Worker
# 使用 Wrangler v4 的新格式
[assets]
directory = "./public"

# 環境變數
[vars]
ENVIRONMENT = "production"


[[routes]]
pattern = "cardioanalytics.twinhao.com"
custom_domain = true
